name: Docker build and push

on:
  push:
    # Publish `$default-branch` as Docker `latest` image.
    branches:
      - $default-branch
      - master
  schedule:
    # rebuild image every week (includes also package updates)
    - cron: '5 3 * * 0'
  workflow_dispatch:

env:
  IMAGE_NAME: apache-wsgi

jobs:
  multi-arch-build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: |
            ${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest

